APPNAME: '<App Name> BackOffice'
MAIL_ADDRESS:    ''
MAIL_PORT:       25
MAIL_DOMAIN:     ''
MAIL_USER_NAME:  ''
MAIL_PASSWORD:   ''
YOUTUBE_KEY: ""
S3_KEY: ""
S3_SECRET: ""
S3_REGION: ""
S3_BUCKET: ""
