APPNAME: '<App Name> BackOffice'
DROPBOX_APP_KEY: ""
DROPBOX_APP_SECRET: ""
DROPBOX_ACCESS_TOKEN: ""
DROPBOX_ACCESS_TOKEN_SECRET: ""
DROPBOX_USER_ID: ""
DROPBOX_ACCESS_TYPE: ""
MAIL_ADDRESS:    ''
MAIL_PORT:       25
MAIL_DOMAIN:     ''
MAIL_USER_NAME:  ''
MAIL_PASSWORD:   ''
YOUTUBE_KEY: ""
